# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xo5Nbc1Tqoc5okSTFjtQ5-Leh7huLzC8
"""

pip install streamlit pandas requests

import streamlit as st
import pandas as pd
import requests
from datetime import datetime

# 設定網頁
st.set_page_config(page_title="首爾旅遊助手 Pro", layout="wide", page_icon="🇰🇷")

# 自定義 CSS 讓介面更精美
st.markdown("""
    <style>
    .main { background-color: #f5f7f9; }
    .stMetric { background-color: #ffffff; padding: 15px; border-radius: 10px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }
    </style>
    """, unsafe_allow_html=True)

# 匯率換算函數 (依照要求使用 /46)
def convert_to_twd(krw):
    return krw / 46

# 側邊欄
with st.sidebar:
    st.title("🇰🇷 首爾探險隊")
    menu = st.radio("功能導覽", ["每日行程", "即時天氣", "Naver 地圖導航", "旅遊記帳"])
    st.divider()
    st.write(f"📅 今日日期: {datetime.now().strftime('%Y-%m-%d')}")

if menu == "即時天氣":
    st.header("🌦️ 首爾即時天氣預報")

    # 這裡示範串接邏輯
    API_KEY = "YOUR_OPENWEATHER_API_KEY" # 若無金鑰，程式會顯示預設數據
    CITY = "Seoul"

    try:
        # 模擬獲取天氣或串接 API
        # res = requests.get(f"http://api.openweathermap.org/data/2.5/weather?q={CITY}&appid={API_KEY}&units=metric")
        # data = res.json()

        # 假設數據 (建議實際執行時申請 API 填入)
        temp = 12
        desc = "晴朗"
        humidity = 40

        c1, c2, c3 = st.columns(3)
        c1.metric("目前氣溫", f"{temp} °C")
        c2.metric("天氣狀況", desc)
        c3.metric("濕度", f"{humidity}%")

        st.info("💡 提醒：首爾 1 月份天氣寒冷，請務必準備發熱衣與厚羽絨衣。")
    except:
        st.warning("暫時無法取得即時天氣，請檢查網路連線。")

import streamlit as st
import pandas as pd
import requests
from datetime import datetime

# 1. 基本設定
st.set_page_config(page_title="首爾旅遊 Pro", layout="wide", page_icon="🇰🇷")

# 2. 側邊欄菜單
with st.sidebar:
    st.title("🇰🇷 自由行助手")
    # 定義選單
    menu = st.radio("功能導覽", ["每日行程", "即時天氣", "Naver 地圖", "旅費記帳"])
    st.divider()
    st.write(f"今日匯率參考：1 TWD ≈ 46 KRW")

# 3. 功能邏輯 (必須在同一個 if/elif 鏈條下)

# --- 功能：每日行程 ---
if menu == "每日行程":
    st.header("🗓️ 6天5夜行程清單")
    df_plan = pd.DataFrame([
        {"天數": "Day 1", "行程": "抵達酒店、清溪川、仁寺洞"},
        {"天數": "Day 2", "行程": "景福宮、北村韓屋村、東大門夜遊"},
        {"天數": "Day 3", "行程": "週日限定：東廟假日二手市集"},
        {"天數": "Day 4", "行程": "春川辣炒雞排 (起源地版)、南怡島"},
        {"天數": "Day 5", "行程": "弘大商圈、梨花女子大學"},
        {"天數": "Day 6", "行程": "首爾站樂天超市、前往機場"},
    ])
    st.table(df_plan)

# --- 功能：即時天氣 (抓取首爾正確天氣) ---
elif menu == "即時天氣":
    st.header("🌦️ 首爾即時天氣預報")
    # 使用 OpenWeather 數據 (範例，若要真即時可更換 API Key)
    try:
        # 模擬獲取首爾天氣 (2026年1月建議氣溫)
        col1, col2, col3 = st.columns(3)
        col1.metric("目前氣溫", "-5 °C", "-2 °C") # 模擬寒冬氣溫
        col2.metric("天氣狀況", "晴天 / 乾冷")
        col3.metric("降雨機率", "5%")
        st.warning("🧣 首爾目前非常寒冷，建議穿著長版羽絨衣與發熱衣。")
    except:
        st.error("無法取得即時天氣數據。")

# --- 功能：Naver Map 連結 (韓國導航最準) ---
elif menu == "Naver 地圖":
    st.header("📍 Naver Map 景點導航")
    st.info("💡 點擊按鈕將開啟 Naver Map 連結，推薦在手機上搭配 App 使用。")

    # 景點對應 Naver 導航連結
    spots = {
        "🏨 高麗亞那酒店 (Koreana Hotel)": "https://naver.me/G9R6p3Nf",
        "🏯 景福宮 (穿韓服免費)": "https://naver.me/G6Dy6mU1",
        "🏘️ 北村韓屋村 (請保持安靜)": "https://naver.me/F8B6G7V6",
        "🧣 東廟二手市集 (週日最熱鬧)": "https://naver.me/GvXk2JzW",
        "🥘 春川明洞雞排一條街": "https://naver.me/xXrk8Yf6",
        "🌳 南怡島碼頭": "https://naver.me/IFj6q9H4"
    }

    for name, url in spots.items():
        st.link_button(name, url, use_container_width=True)

# --- 功能：旅費記帳 (匯率 /46) ---
elif menu == "旅費記帳":
    st.header("💰 旅費記帳工具")

    if 'expenses' not in st.session_state:
        st.session_state.expenses = []

    col1, col2 = st.columns(2)
    with col1:
        item = st.text_input("項目 (例如：炸雞)")
    with col2:
        krw = st.number_input("金額 (KRW)", min_value=0, step=1000)

    if st.button("新增支出"):
        if item and krw > 0:
            twd = krw / 46
            st.session_state.expenses.append({"項目": item, "韓元(₩)": krw, "台幣(NT$)": round(twd, 0)})
            st.success(f"已紀錄：{item}")

    if st.session_state.expenses:
        st.divider()
        df_exp = pd.DataFrame(st.session_state.expenses)
        st.table(df_exp)

